title: Econ-ARK
url: https://econ-ark.org/
author: Econ-ARK
keywords: 
description: "Structural modeling economic choices of heterogeneous agents"

timezone: America/Los_Angeles
google_analytics: UA-118130489-1

baseurl: /econark-jekyll-theme/
#baseurl: 

sass:
   sass_dir: /assets/sass
   style: :compressed

repository: 

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle

collections:
  demonstrations:
  instructional:
  presentations:
  replications:
  team:

